---
title: "Assignment: AI-assisted Code Reviews"
author: "Xingrong Zong"
date: "`r Sys.Date()`"
output: html_document
---

# Assignment: AI-assisted Code Reviews

## Causal Assumptions
Outcomes:
- `extent`: Number of characters in the code review.
- `quality`: Subjective quality of the code review as assessed by experts (where 1 is bad and 5 good quality).
- `result`:Whether the code review contributed to making a decision on the pull request (1) or not (0).

Predictors:
- `age`: Age of the reviewer in number of years.
- `skill`: Skill of a reviewer measured on a continuous scale.
- `used.cr.technology`: Whether the reviewer uses AI-support during code review (1) or not(0).
- `complexity`: Relative complexity of the code change to be reviewed. 

### DAG 1：
Selection + Confounding + Mediation
- `age` -> `skill` (experience rises with age)
- `age` -> `used.cr.technology` (older engineers are less likely to adopt AI)
- `skill` -> `extent` & `quality` (more skilled reviewers write more concise and higher quality reviews)
- `complexity` -> `extent` & `quality `(more complex code changes require longer reviews and harder to review well)
- `extent` & `quality` -> `result`,  (longer reviews are more likely to influence decisions)
- `used.cr.technology` -> `extent` & `quality` (AI-assisted can change length and clarity of reviews)
Aversion: AI → Result (direct negative path, “categorically discarded more often”)

Predictors (independent variables): `used.cr.technology`.
Confounders: `age`, `skill`, `complexity`.
Mediators: `extent`, `quality`.
Outcomes (dependent variables): `result`.

Therefore, 
- `age`, `skill`, and `complexity` are confounders that influence both the predictor `used.cr.technology` and the outcomes `extent`, `quality`, and `result`.
- `extent` and `quality` are mediators that lie on the causal path between the predictor `used.cr.technology` and the outcome `result`.

This DAG supports total vs direct effect reasoning:
- Total effect of `used.cr.technology` on `result` without conditioning on mediators `extent` and `quality`.
- Direct effect of `used.cr.technology` on `result` conditioning on mediators `extent` and `quality` and confounders `age`, `skill`, and `complexity`.

### DAG 2：

